apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  config : |
    server {
        # Process request to any host
        server_name  _;
        listen       8080;
        error_log    /var/log/nginx/error.log;
        access_log   /var/log/nginx/access.log;
        root         /var/www/html;
        index        index.php index.html;

        # The `last` flag tells NGINX to skip any subsequent Rewrite‑module directives in the current server or location block
        # and start a search for a new location that matches the rewritten URL
        location ~ /api/ {
            if (!-e $request_filename) {
                rewrite ^/(.*)$ /public/index.php?q=$1 last;
            }
        }

        location ~ \.php$ {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
            fastcgi_pass   php:9000;
        }
    }
