# You may want to mount /var/www/html/log as a PersistentVolume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      # You may want to mount /var/www/html/log as a PersistentVolume
      # Specify dedicated volume for logs
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-pvc
      # We need to chown -R www-data:www-data /var/www/html/log
      initContainers:
        - name: volume-mount-chown
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "--"
          args:
            - "chown -R 33:33 /var/www/html/log"
          volumeMounts:
            - name: log-volume
              mountPath: /var/www/html/log
      containers:
        - name: app
          image: sunsingerus/bootstrapi:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          # You may want to mount /var/www/html/log as a PersistentVolume
          # Mount dedicated volume for logs
          volumeMounts:
            - name: log-volume
              mountPath: /var/www/html/log
